version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/__init__.py
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=city_car_management
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: